server: 
  port: 8889
app:
  datasource:
    first:
      xa-properties.url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      xa-properties.user: root
      xa-properties.password: newpass
      xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      unique-resource-name: first
    second:
      xa-properties.url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      xa-properties.user: root
      xa-properties.password: newpass
      xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      unique-resource-name: second
spring:
  jta:
    # Transaction manager unique identifier.
    transaction-manager-id: atomikos-transaction
    # Transaction logs directory.
    log-dir:
